import type { Job } from "./types";

// Helper function to generate contact info
const createContactInfo = (name: string, domain: string) => ({
  email: `${name.toLowerCase().replace(/\s+/g, ".")}@${domain}`,
  phone: `+1 (415) ${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
  contactPerson: name.includes(" ") ? name.split(" ")[0] + " Manager" : `${name} Contact`,
});

export const initialJobsA: Job[] = [
  {
    id: "job-5",
    customerName: "Twin Peaks",
    address: "501 Twin Peaks Blvd, San Francisco, CA 94114",
    scheduledTime: "02:30 PM",
    coordinates: [-122.4475, 37.7545],
    date: "2024-11-10",
    contactInfo: createContactInfo("Twin Peaks", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 450.00,
    paymentDueDate: "2024-11-05",
    notes: "Access via main entrance. Parking available on site.",
  },
  {
    id: "job-2",
    customerName: "Coit Tower",
    address: "1 Telegraph Hill Blvd, San Francisco, CA 94133",
    scheduledTime: "10:00 AM",
    coordinates: [-122.4058, 37.8024],
    date: "2024-11-10",
    contactInfo: createContactInfo("Coit Tower", "example.com"),
    paymentStatus: "pending",
    paymentAmount: 320.00,
    paymentDueDate: "2024-11-15",
    notes: "Elevator access required. Contact security before arrival.",
  },
  {
    id: "job-4",
    customerName: "Alamo Square Park",
    address: "Steiner St & Hayes St, San Francisco, CA 94117",
    scheduledTime: "01:00 PM",
    coordinates: [-122.433, 37.776],
    date: "2024-11-10",
    contactInfo: createContactInfo("Alamo Square", "example.com"),
    paymentStatus: "overdue",
    paymentAmount: 280.00,
    paymentDueDate: "2024-11-01",
    notes: "Public park area. No special access needed.",
  },
  {
    id: "job-1",
    customerName: "Ferry Building Marketplace",
    address: "1 Ferry Building, San Francisco, CA 94111",
    scheduledTime: "09:00 AM",
    coordinates: [-122.3932, 37.7956],
    date: "2024-11-10",
    contactInfo: createContactInfo("Ferry Building", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 550.00,
    paymentDueDate: "2024-11-05",
    notes: "Main entrance on Embarcadero. High traffic area - schedule early.",
  },
  {
    id: "job-3",
    customerName: "Palace of Fine Arts",
    address: "3601 Lyon St, San Francisco, CA 94123",
    scheduledTime: "11:30 AM",
    coordinates: [-122.4486, 37.8021],
    date: "2024-11-10",
    contactInfo: createContactInfo("Palace Fine Arts", "example.com"),
    paymentStatus: "partial",
    paymentAmount: 400.00,
    paymentDueDate: "2024-11-12",
    notes: "Historic building. Please be respectful of the architecture.",
  },
];

export const initialJobsB: Job[] = [
  {
    id: "job-10",
    customerName: "de Young Museum",
    address: "50 Hagiwara Tea Garden Dr, San Francisco, CA 94118",
    scheduledTime: "03:00 PM",
    coordinates: [-122.468, 37.771],
    date: "2024-11-11",
    contactInfo: createContactInfo("de Young Museum", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 600.00,
    paymentDueDate: "2024-11-08",
    notes: "Museum entrance. Contact curator for access.",
  },
  {
    id: "job-6",
    customerName: "Alcatraz Island",
    address: "Alcatraz Island, San Francisco, CA 94133",
    scheduledTime: "09:30 AM",
    coordinates: [-122.423, 37.827],
    date: "2024-11-11",
    contactInfo: createContactInfo("Alcatraz Island", "example.com"),
    paymentStatus: "pending",
    paymentAmount: 750.00,
    paymentDueDate: "2024-11-18",
    notes: "Ferry required. Book tickets in advance.",
  },
  {
    id: "job-8",
    customerName: "Ghirardelli Square",
    address: "900 North Point St, San Francisco, CA 94109",
    scheduledTime: "12:00 PM",
    coordinates: [-122.422, 37.806],
    date: "2024-11-11",
    contactInfo: createContactInfo("Ghirardelli Square", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 380.00,
    paymentDueDate: "2024-11-06",
    notes: "Tourist area. High foot traffic expected.",
  },
  {
    id: "job-9",
    customerName: "Oracle Park",
    address: "24 Willie Mays Plaza, San Francisco, CA 94107",
    scheduledTime: "01:30 PM",
    coordinates: [-122.389, 37.778],
    date: "2024-11-11",
    contactInfo: createContactInfo("Oracle Park", "example.com"),
    paymentStatus: "partial",
    paymentAmount: 520.00,
    paymentDueDate: "2024-11-14",
    notes: "Stadium access. Check for game schedules.",
  },
  {
    id: "job-7",
    customerName: "Lombard Street",
    address: "1070 Lombard St, San Francisco, CA 94109",
    scheduledTime: "10:45 AM",
    coordinates: [-122.419, 37.802],
    date: "2024-11-11",
    contactInfo: createContactInfo("Lombard Street", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 290.00,
    paymentDueDate: "2024-11-07",
    notes: "Famous winding street. Limited parking.",
  },
];

// Jobs for 11/12
export const initialJobsC: Job[] = [
  {
    id: "job-12-1",
    customerName: "Golden Gate Park",
    address: "Golden Gate Park, San Francisco, CA 94117",
    scheduledTime: "09:00 AM",
    coordinates: [-122.455, 37.769],
    date: "2024-11-12",
    contactInfo: createContactInfo("Golden Gate Park", "example.com"),
    paymentStatus: "pending",
    paymentAmount: 420.00,
    paymentDueDate: "2024-11-16",
    notes: "Large park area. Multiple entry points available.",
  },
  {
    id: "job-12-2",
    customerName: "Mission Dolores Park",
    address: "Dolores St & 19th St, San Francisco, CA 94114",
    scheduledTime: "11:00 AM",
    coordinates: [-122.426, 37.759],
    date: "2024-11-12",
    contactInfo: createContactInfo("Mission Dolores", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 350.00,
    paymentDueDate: "2024-11-09",
    notes: "Popular park. Weekend crowds expected.",
  },
  {
    id: "job-12-3",
    customerName: "Painted Ladies",
    address: "Steiner St & Hayes St, San Francisco, CA 94117",
    scheduledTime: "02:00 PM",
    coordinates: [-122.433, 37.776],
    date: "2024-11-12",
    contactInfo: createContactInfo("Painted Ladies", "example.com"),
    paymentStatus: "overdue",
    paymentAmount: 310.00,
    paymentDueDate: "2024-11-03",
    notes: "Historic Victorian houses. Photo-friendly location.",
  },
];

// Jobs for 11/13
export const initialJobsD: Job[] = [
  {
    id: "job-13-1",
    customerName: "Chinatown",
    address: "Grant Ave & Bush St, San Francisco, CA 94108",
    scheduledTime: "10:00 AM",
    coordinates: [-122.407, 37.794],
    date: "2024-11-13",
    contactInfo: createContactInfo("Chinatown", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 480.00,
    paymentDueDate: "2024-11-10",
    notes: "Busy commercial area. Street parking limited.",
  },
  {
    id: "job-13-2",
    customerName: "North Beach",
    address: "Columbus Ave & Grant Ave, San Francisco, CA 94133",
    scheduledTime: "12:30 PM",
    coordinates: [-122.407, 37.801],
    date: "2024-11-13",
    contactInfo: createContactInfo("North Beach", "example.com"),
    paymentStatus: "pending",
    paymentAmount: 390.00,
    paymentDueDate: "2024-11-17",
    notes: "Italian neighborhood. Great restaurants nearby.",
  },
  {
    id: "job-13-3",
    customerName: "Embarcadero",
    address: "Embarcadero, San Francisco, CA 94111",
    scheduledTime: "03:00 PM",
    coordinates: [-122.397, 37.795],
    date: "2024-11-13",
    contactInfo: createContactInfo("Embarcadero", "example.com"),
    paymentStatus: "partial",
    paymentAmount: 440.00,
    paymentDueDate: "2024-11-15",
    notes: "Waterfront area. Beautiful views of the bay.",
  },
];

export const candidateJobs: Job[] = [
  {
    id: "candidate-1",
    customerName: "California Academy of Sciences",
    address: "55 Music Concourse Dr, San Francisco, CA 94118",
    scheduledTime: "04:00 PM",
    coordinates: [-122.466, 37.77],
    date: "2024-11-10", // Default date, will be updated when added
    contactInfo: createContactInfo("Academy Sciences", "example.com"),
    paymentStatus: "pending",
    paymentAmount: 650.00,
    paymentDueDate: "2024-11-19",
    notes: "Science museum. Family-friendly location.",
  },
  {
    id: "candidate-2",
    customerName: "Fisherman's Wharf",
    address: "Jefferson St, San Francisco, CA 94133",
    scheduledTime: "04:00 PM",
    coordinates: [-122.417, 37.808],
    date: "2024-11-10",
    contactInfo: createContactInfo("Fisherman Wharf", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 500.00,
    paymentDueDate: "2024-11-11",
    notes: "Tourist hotspot. Seafood restaurants nearby.",
  },
  {
    id: "candidate-3",
    customerName: "Sutro Baths",
    address: "1004 Point Lobos Ave, San Francisco, CA 94121",
    scheduledTime: "04:00 PM",
    coordinates: [-122.514, 37.78],
    date: "2024-11-10",
    contactInfo: createContactInfo("Sutro Baths", "example.com"),
    paymentStatus: "overdue",
    paymentAmount: 360.00,
    paymentDueDate: "2024-11-02",
    notes: "Historic ruins. Ocean views. Windy conditions.",
  },
  {
    id: "candidate-4",
    customerName: "Golden Gate Bridge Pavilion",
    address: "Golden Gate Bridge, San Francisco, CA 94129",
    scheduledTime: "04:00 PM",
    coordinates: [-122.4783, 37.8079],
    date: "2024-11-10",
    contactInfo: createContactInfo("Golden Gate Bridge", "example.com"),
    paymentStatus: "paid",
    paymentAmount: 580.00,
    paymentDueDate: "2024-11-12",
    notes: "Iconic landmark. Visitor center available.",
  },
];

export const initialJobs = [...initialJobsA, ...initialJobsB];
